### ISSUE TITLE
First model, predict winner given heroes selected

### ISSUE THREAD

**Issue by Vector-S** [AlphaTac/AlphaCore#2]
开始时间：2018/05/05

截止时间：2018/06/01 (待议)

目标：
- [ ] 在仅仅知道对阵双方team_id的情况下，预测某一方赢[x]。
- [x] 在给出ban-pick之后，预测某一方赢的概率。

- [ ] 给出当前ban（pick）的英雄，预测下一手最可能ban（pick）的英雄，并推荐下一手ban（pick）的英雄。

**Comment by PeiShang** [comment]
目标：
1. 在仅仅知道对阵双方team_id的情况下，预测某一方赢的概率。
2. 在给出ban-pick之后，预测某一方赢的概率。
3. 给出当前ban（pick）的英雄，预测下一手最可能ban（pick）的英雄，并推荐下一手ban（pick）的英雄。
